export enum Category {
  SQL_INJECTION = 'SQL_INJECTION',
  XSS = 'XSS',
  AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE',
  INSECURE_DATA_HANDLING = 'INSECURE_DATA_HANDLING',
  DEPENDENCY_VULNERABILITY = 'DEPENDENCY_VULNERABILITY',
}

export enum Framework {
  ISO_27001 = 'ISO_27001',
  OWASP_TOP_10_2021 = 'OWASP_TOP_10_2021',
  OWASP_ASVS = 'OWASP_ASVS',
  CLAUDE_CODE_SECURITY = 'CLAUDE_CODE_SECURITY',
  DEVSECOPS = 'DEVSECOPS',
}

export enum Severity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum RoleType {
  DEVELOPER = 'DEVELOPER',
  AUDITOR = 'AUDITOR',
  SECURITY_ADMIN = 'SECURITY_ADMIN',
}

export enum AnalysisStatus {
  QUEUED = 'QUEUED',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum InventoryStatus {
  PENDING = 'PENDING',
  INVENTORYING = 'INVENTORYING',
  READY_FOR_ANALYSIS = 'READY_FOR_ANALYSIS',
  FAILED = 'FAILED',
}

export enum ArtifactType {
  SOURCE_CODE = 'SOURCE_CODE',
  CONFIG = 'CONFIG',
  DEPENDENCY_MANIFEST = 'DEPENDENCY_MANIFEST',
  DOCUMENTATION = 'DOCUMENTATION',
  INFRASTRUCTURE_AS_CODE = 'INFRASTRUCTURE_AS_CODE',
}

export enum RepositoryStatus {
  UPLOADING = 'UPLOADING',
  READY_FOR_ANALYSIS = 'READY_FOR_ANALYSIS',
  ANALYZING = 'ANALYZING',
  ARCHIVED = 'ARCHIVED',
  EXPIRED = 'EXPIRED',
}
